// Package po
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package po

import (
	enumv1 "github.com/go-micro-saas/organization-service/api/org-service/v1/enums"
	schemas "github.com/go-micro-saas/organization-service/app/org-service/internal/data/schema/org"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
	idpkg "github.com/ikaiguang/go-srv-kit/kit/id"
	errorpkg "github.com/ikaiguang/go-srv-kit/kratos/error"
	datatypes "gorm.io/datatypes"
	"gorm.io/gorm"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// Org ENGINE InnoDB CHARSET utf8mb4 COMMENT '组织'
type Org struct {
	Id              uint64                         `gorm:"column:id;primaryKey" json:"id"`                    // ID
	CreatedTime     time.Time                      `gorm:"column:created_time" json:"created_time"`           // 创建时间
	UpdatedTime     time.Time                      `gorm:"column:updated_time" json:"updated_time"`           // 最后修改时间
	DeletedTime     uint64                         `gorm:"column:deleted_time" json:"deleted_time"`           // 删除时间
	OrgId           uint64                         `gorm:"column:org_id" json:"org_id"`                       // uuid
	OrgName         string                         `gorm:"column:org_name" json:"org_name"`                   // 组织名称
	OrgAvatar       string                         `gorm:"column:org_avatar" json:"org_avatar"`               // 组织头像
	OrgContactName  string                         `gorm:"column:org_contact_name" json:"org_contact_name"`   // 组织联系名称
	OrgContactPhone string                         `gorm:"column:org_contact_phone" json:"org_contact_phone"` // 组织联系手机
	OrgContactEmail string                         `gorm:"column:org_contact_email" json:"org_contact_email"` // 组织联系邮箱
	OrgType         enumv1.OrgTypeEnum_OrgType     `gorm:"column:org_type" json:"org_type"`                   // 组织状态；1：个人版，2：标准组织，3：。。。
	OrgStatus       enumv1.OrgStatusEnum_OrgStatus `gorm:"column:org_status" json:"org_status"`               // 状态；0：INIT，1：ENABLE，2：DISABLE，3：DELETED
	OrgIndustryId   uint64                         `gorm:"column:org_industry_id" json:"org_industry_id"`     // 组织行业
	OrgScaleId      uint64                         `gorm:"column:org_scale_id" json:"org_scale_id"`           // 组织规模
	OrgAddress      string                         `gorm:"column:org_address" json:"org_address"`             // 组织地址
	OrgZipCode      string                         `gorm:"column:org_zip_code" json:"org_zip_code"`           // 组织地址邮编
	OrgCreatorId    uint64                         `gorm:"column:org_creator_id" json:"org_creator_id"`       // 组织创建者
}

func DefaultOrg() *Org {
	dataModel := &Org{
		Id:              0,
		CreatedTime:     time.Now(),
		UpdatedTime:     time.Now(),
		DeletedTime:     0,
		OrgId:           0,
		OrgName:         "",
		OrgAvatar:       "",
		OrgContactName:  "",
		OrgContactPhone: "",
		OrgContactEmail: "",
		OrgType:         enumv1.OrgTypeEnum_STANDARD,
		OrgStatus:       enumv1.OrgStatusEnum_ENABLE,
		OrgIndustryId:   0,
		OrgScaleId:      0,
		OrgAddress:      "",
		OrgZipCode:      "",
		OrgCreatorId:    0,
	}
	return dataModel
}

func DefaultOrgWithID(idGenerator idpkg.Snowflake) (dataModel *Org, err error) {
	dataModel = DefaultOrg()
	dataModel.OrgId, err = idGenerator.NextID()
	if err != nil {
		e := errorpkg.ErrorInternalServer(err.Error())
		return dataModel, errorpkg.WithStack(e)
	}
	return dataModel, err
}

type OrgListParam struct {
	OrgIDList []uint64 // 用户ID列表
	OrgName   string   // 组织名称

	IgnoreDeletedTime bool // 忽略删除时间
	OnlyNotDeleted    bool // 只查询未删除
	OnlyDeleted       bool // 只查询已删除

	PaginatorArgs *gormpkg.PaginatorArgs
}

func (s *OrgListParam) WhereConditions(dbConn *gorm.DB) *gorm.DB {
	if len(s.OrgIDList) == 1 {
		dbConn = dbConn.Where(schemas.OrgSchema.FieldName(schemas.FieldOrgId)+" = ?", s.OrgIDList[0])
	} else if len(s.OrgIDList) > 1 {
		dbConn = dbConn.Where(schemas.OrgSchema.FieldName(schemas.FieldOrgId)+" IN (?)", s.OrgIDList)
	}

	if !s.IgnoreDeletedTime {
		if s.OnlyNotDeleted {
			dbConn = dbConn.Where("deleted_time = ?", 0)
		} else if s.OnlyDeleted {
			dbConn = dbConn.Where("deleted_time > ?", 0)
		}
	}
	
	if len(s.OrgName) > 0 {
		dbConn = dbConn.Where(schemas.OrgSchema.FieldName(schemas.FieldOrgName)+" LIKE ?", "%"+s.OrgName+"%")
	}
	return dbConn
}
