// Package po
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package po

import (
	datatypes "gorm.io/datatypes"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// OrgRecordForUser ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户组织记录'
type OrgRecordForUser struct {
	UserId        uint64    `gorm:"column:user_id;primaryKey" json:"user_id"`      // 用户ID
	CreatedTime   time.Time `gorm:"column:created_time" json:"created_time"`       // 创建时间
	UpdatedTime   time.Time `gorm:"column:updated_time" json:"updated_time"`       // 最后修改时间
	PersonalOrgId uint64    `gorm:"column:personal_org_id" json:"personal_org_id"` // 个人组织ID
	LastOrgId     uint64    `gorm:"column:last_org_id" json:"last_org_id"`         // 最后的组织ID
}
