org_service:
  snowflake:
    enable: false
    instance_id: "${app.project_name}/${app.server_name}/${app.server_env}/${app.server_version}"
    instance_name: "org-service"
    metadata:
      service: org-service
  business_setting:
    user_create_org_max_count: 10
    user_belong_org_max_count: 20
