org_service:
  snowflake:
    enable: true
    instance_id: "${app.project_name}/${app.server_name}/${app.server_env}/${app.server_version}"
    instance_name: "org-service"
    metadata:
      service: org-service
