// Package data
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package data

import (
	"bytes"
	context "context"
	enumv1 "github.com/go-micro-saas/organization-service/api/org-service/v1/enums"
	"github.com/go-micro-saas/organization-service/app/org-service/internal/data/po"
	datarepos "github.com/go-micro-saas/organization-service/app/org-service/internal/data/repo"
	schemas "github.com/go-micro-saas/organization-service/app/org-service/internal/data/schema/org_employee"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
	errorpkg "github.com/ikaiguang/go-srv-kit/kratos/error"
	gorm "gorm.io/gorm"
	"strings"
)

// orgEmployeeRepo repo
type orgEmployeeRepo struct {
	dbConn            *gorm.DB            // *gorm.DB
	OrgEmployeeSchema schemas.OrgEmployee // OrgEmployee
}

// NewOrgEmployeeRepo new data repo
func NewOrgEmployeeRepo(dbConn *gorm.DB) datarepos.OrgEmployeeRepo {
	return &orgEmployeeRepo{
		dbConn: dbConn,
	}
}

// =============== 创建 ===============

// create insert one
func (s *orgEmployeeRepo) create(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Create(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Create insert one
func (s *orgEmployeeRepo) Create(ctx context.Context, dataModel *po.OrgEmployee) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *orgEmployeeRepo) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) error {
	return s.create(ctx, dbConn, dataModel)
}

func (s *orgEmployeeRepo) CreateWithTransaction(ctx context.Context, tx gormpkg.TransactionInterface, dataModel *po.OrgEmployee) (err error) {
	fc := func(ctx context.Context, tx *gorm.DB) error {
		return s.create(ctx, tx, dataModel)
	}
	err = tx.Do(ctx, fc)
	if err != nil {
		return err
	}
	return
}

// existCreate exist create
func (s *orgEmployeeRepo) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.existCreateByEmployeeUUID(ctx, dbConn, dataModel.EmployeeUuid)
}

// existCreate exist create
func (s *orgEmployeeRepo) existCreateByEmployeeUUID(ctx context.Context, dbConn *gorm.DB, uuid string) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	anotherModel = new(po.OrgEmployee)
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldEmployeeUuid+" = ?", uuid).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *orgEmployeeRepo) ExistCreate(ctx context.Context, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

func (s *orgEmployeeRepo) ExistCreateByEmployeeUUID(ctx context.Context, employeeUUID string) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.existCreateByEmployeeUUID(ctx, s.dbConn, employeeUUID)
}

// ExistCreateWithDBConn exist create
func (s *orgEmployeeRepo) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *orgEmployeeRepo) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*po.OrgEmployee, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// CreateInBatches create many
func (s *orgEmployeeRepo) CreateInBatches(ctx context.Context, dataModels []*po.OrgEmployee, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *orgEmployeeRepo) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.OrgEmployee, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *orgEmployeeRepo) update(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		// Where(schemas.FieldId+" = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Update update
func (s *orgEmployeeRepo) Update(ctx context.Context, dataModel *po.OrgEmployee) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *orgEmployeeRepo) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) error {
	return s.update(ctx, dbConn, dataModel)
}

// existUpdate exist update
func (s *orgEmployeeRepo) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	anotherModel = new(po.OrgEmployee)
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		Where(schemas.FieldId+" != ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *orgEmployeeRepo) ExistUpdate(ctx context.Context, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *orgEmployeeRepo) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

func (s *orgEmployeeRepo) SetOrgEmployeeStatus(ctx context.Context, dataModel *po.OrgEmployee) (err error) {
	updates := map[string]interface{}{
		schemas.FieldUpdatedTime:      dataModel.UpdatedTime,
		schemas.FieldEmployeeStatus:   dataModel.EmployeeStatus,
		schemas.FieldModifyStatusTime: dataModel.ModifyStatusTime,
	}
	err = s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		UpdateColumns(updates).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

func (s *orgEmployeeRepo) RemoveOrgEmployee(ctx context.Context, dataModel *po.OrgEmployee) (err error) {
	updates := map[string]interface{}{
		schemas.FieldUpdatedTime:      dataModel.UpdatedTime,
		schemas.FieldEmployeeUuid:     dataModel.EmployeeUuid,
		schemas.FieldEmployeeStatus:   dataModel.EmployeeStatus,
		schemas.FieldModifyStatusTime: dataModel.ModifyStatusTime,
		schemas.FieldDeletedTime:      dataModel.DeletedTime,
	}
	err = s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		UpdateColumns(updates).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

func (s *orgEmployeeRepo) SetOrgEmployeeRole(ctx context.Context, dataModel *po.OrgEmployee) (err error) {
	updates := map[string]interface{}{
		schemas.FieldUpdatedTime:    dataModel.UpdatedTime,
		schemas.FieldEmployeeRole:   dataModel.EmployeeRole,
		schemas.FieldModifyRoleTime: dataModel.ModifyRoleTime,
	}
	err = s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		UpdateColumns(updates).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// =============== query one : 查一个 ===============

// queryOneById query one by id
func (s *orgEmployeeRepo) queryOneById(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	dataModel = new(po.OrgEmployee)
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" = ?", id).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneById query one by id
func (s *orgEmployeeRepo) QueryOneById(ctx context.Context, id interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.queryOneById(ctx, s.dbConn, id)
}

// QueryOneByIdWithDBConn query one by id
func (s *orgEmployeeRepo) QueryOneByIdWithDBConn(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.queryOneById(ctx, dbConn, id)
}

func (s *orgEmployeeRepo) QueryOneEmployee(ctx context.Context, param *po.QueryEmployeeParam) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	dataModel = new(po.OrgEmployee)
	dbConn := s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldOrgId+" = ?", param.OrgID).
		Where(schemas.FieldUserId+" = ?", param.UserID).
		Where(schemas.FieldDeletedTime+" = ?", 0)

	dbConn = po.WhereDefaultOrgEmployeeStatus(dbConn)
	err = dbConn.First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

func (s *orgEmployeeRepo) QueryLastByUserID(ctx context.Context, userID uint64) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	dataModel = new(po.OrgEmployee)
	dbConn := s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldUserId+" = ?", userID).
		Where(schemas.FieldDeletedTime+" = ?", 0).
		Where(schemas.FieldEmployeeStatus+" = ?", enumv1.OrgEmployeeStatusEnum_ENABLE).
		Order(schemas.FieldCreatedTime + " DESC")

	err = dbConn.First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

func (s *orgEmployeeRepo) QueryOneByEmployeeID(ctx context.Context, employeeID uint64) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	dataModel = new(po.OrgEmployee)
	err = s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldEmployeeId+" = ?", employeeID).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

func (s *orgEmployeeRepo) QueryByEmployeeIDList(ctx context.Context, employeeIDList []uint64) ([]*po.OrgEmployee, error) {
	if len(employeeIDList) == 0 {
		return nil, nil
	}
	var dataModels []*po.OrgEmployee
	err := s.dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldEmployeeId+" in (?)", employeeIDList).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return nil, err
	}
	return dataModels, nil
}

// queryOneByConditions query one by conditions
func (s *orgEmployeeRepo) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	dataModel = new(po.OrgEmployee)
	dbConn = dbConn.WithContext(ctx).Table(s.OrgEmployeeSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *orgEmployeeRepo) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *orgEmployeeRepo) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

func (s *orgEmployeeRepo) QueryUserEmployeeList(ctx context.Context, queryParam *po.UserEmployeeList) (dataModels []*po.OrgEmployee, err error) {
	// query where
	dbConn := s.dbConn.WithContext(ctx).Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldUserId+" = ?", queryParam.UserID).
		Where(schemas.FieldDeletedTime+" = ?", 0)

	dbConn = po.WhereDefaultOrgEmployeeStatus(dbConn)
	err = dbConn.Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

func (s *orgEmployeeRepo) QueryUserEmployeeRole(ctx context.Context, queryParam *po.UserEmployeeList) (dataModels []*po.OrgEmployeeRole, err error) {
	// query where
	selectFields := (&po.OrgEmployeeRole{}).SelectFields()
	dbConn := s.dbConn.WithContext(ctx).Table(s.OrgEmployeeSchema.TableName()).
		Select(selectFields).
		Where(schemas.FieldUserId+" = ?", queryParam.UserID).
		Where(schemas.FieldDeletedTime+" = ?", 0)

	dbConn = po.WhereDefaultOrgEmployeeStatus(dbConn)
	err = dbConn.Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *orgEmployeeRepo) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*po.OrgEmployee, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.OrgEmployeeSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *orgEmployeeRepo) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*po.OrgEmployee, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *orgEmployeeRepo) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*po.OrgEmployee, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *orgEmployeeRepo) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.OrgEmployee, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.OrgEmployeeSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormpkg.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormpkg.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormpkg.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// List 列表
func (s *orgEmployeeRepo) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.OrgEmployee, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *orgEmployeeRepo) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.OrgEmployee, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

func (s *orgEmployeeRepo) ListOrgEmployee(ctx context.Context, queryParam *po.OrgEmployeeListParam, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.OrgEmployee, recordCount int64, err error) {
	// query where
	dbConn := s.dbConn.WithContext(ctx).Table(s.OrgEmployeeSchema.TableName())
	dbConn = queryParam.WhereConditions(dbConn)
	dbConn = gormpkg.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormpkg.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormpkg.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// =============== delete : 删除 ===============

// delete delete one
func (s *orgEmployeeRepo) delete(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		Delete(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// Delete delete one
func (s *orgEmployeeRepo) Delete(ctx context.Context, dataModel *po.OrgEmployee) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *orgEmployeeRepo) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgEmployee) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *orgEmployeeRepo) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgEmployeeSchema.TableName()).
		Where(schemas.FieldId+" in (?)", ids).
		Delete(po.OrgEmployee{}).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *orgEmployeeRepo) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *orgEmployeeRepo) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormpkg.BatchInsertRepo = new(OrgEmployeeSlice)

// OrgEmployeeSlice 表切片
type OrgEmployeeSlice []*po.OrgEmployee

// TableName 表名
func (s *OrgEmployeeSlice) TableName() string {
	return schemas.OrgEmployeeSchema.TableName()
}

// Len 长度
func (s *OrgEmployeeSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *OrgEmployeeSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime, schemas.FieldUpdatedTime,
		schemas.FieldDeletedTime, schemas.FieldEmployeeId,
		schemas.FieldUserId, schemas.FieldOrgId,
		schemas.FieldEmployeeName, schemas.FieldEmployeeAvatar,
		schemas.FieldEmployeePhone, schemas.FieldEmployeeEmail,
		schemas.FieldEmployeeRole, schemas.FieldEmployeeStatus,
		schemas.FieldInviterRecordId, schemas.FieldInviterUserId,
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *OrgEmployeeSlice) InsertValues(args *gormpkg.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].DeletedTime)
		prepareData = append(prepareData, dataModels[index].EmployeeId)
		prepareData = append(prepareData, dataModels[index].UserId)
		prepareData = append(prepareData, dataModels[index].OrgId)
		prepareData = append(prepareData, dataModels[index].EmployeeName)
		prepareData = append(prepareData, dataModels[index].EmployeeAvatar)
		prepareData = append(prepareData, dataModels[index].EmployeePhone)
		prepareData = append(prepareData, dataModels[index].EmployeeEmail)
		prepareData = append(prepareData, dataModels[index].EmployeeRole)
		prepareData = append(prepareData, dataModels[index].EmployeeStatus)
		prepareData = append(prepareData, dataModels[index].InviterRecordId)
		prepareData = append(prepareData, dataModels[index].InviterUserId)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *OrgEmployeeSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime + "=excluded." + schemas.FieldCreatedTime,
		schemas.FieldUpdatedTime + "=excluded." + schemas.FieldUpdatedTime,
		schemas.FieldDeletedTime + "=excluded." + schemas.FieldDeletedTime,
		schemas.FieldEmployeeId + "=excluded." + schemas.FieldEmployeeId,
		schemas.FieldUserId + "=excluded." + schemas.FieldUserId,
		schemas.FieldOrgId + "=excluded." + schemas.FieldOrgId,
		schemas.FieldEmployeeName + "=excluded." + schemas.FieldEmployeeName,
		schemas.FieldEmployeeAvatar + "=excluded." + schemas.FieldEmployeeAvatar,
		schemas.FieldEmployeePhone + "=excluded." + schemas.FieldEmployeePhone,
		schemas.FieldEmployeeEmail + "=excluded." + schemas.FieldEmployeeEmail,
		schemas.FieldEmployeeRole + "=excluded." + schemas.FieldEmployeeRole,
		schemas.FieldEmployeeStatus + "=excluded." + schemas.FieldEmployeeStatus,
		schemas.FieldInviterRecordId + "=excluded." + schemas.FieldInviterRecordId,
		schemas.FieldInviterUserId + "=excluded." + schemas.FieldInviterUserId,
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *OrgEmployeeSlice) ConflictActionForMySQL() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *OrgEmployeeSlice) ConflictActionForPostgres() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *orgEmployeeRepo) insert(ctx context.Context, dbConn *gorm.DB, dataModels OrgEmployeeSlice) error {
	err := gormpkg.BatchInsertWithContext(ctx, dbConn, &dataModels)
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return nil
}

// Insert 批量插入
func (s *orgEmployeeRepo) Insert(ctx context.Context, dataModels []*po.OrgEmployee) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *orgEmployeeRepo) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.OrgEmployee) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *orgEmployeeRepo) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	// tableName := s.OrgEmployeeSchema.TableName()

	// On-demand loading

	// id
	// if data, ok := conditions[schemas.FieldId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldId+" = ?", data)
	// }

	// created_time
	// if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldCreatedTime+" = ?", data)
	// }

	// updated_time
	// if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUpdatedTime+" = ?", data)
	// }

	// deleted_time
	// if data, ok := conditions[schemas.FieldDeletedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldDeletedTime+" = ?", data)
	// }

	// employee_id
	// if data, ok := conditions[schemas.FieldEmployeeId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeeId+" = ?", data)
	// }

	// user_id
	// if data, ok := conditions[schemas.FieldUserId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserId+" = ?", data)
	// }

	// org_id
	// if data, ok := conditions[schemas.FieldOrgId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldOrgId+" = ?", data)
	// }

	// employee_name
	// if data, ok := conditions[schemas.FieldEmployeeName]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeeName+" = ?", data)
	// }

	// employee_avatar
	// if data, ok := conditions[schemas.FieldEmployeeAvatar]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeeAvatar+" = ?", data)
	// }

	// employee_phone
	// if data, ok := conditions[schemas.FieldEmployeePhone]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeePhone+" = ?", data)
	// }

	// employee_email
	// if data, ok := conditions[schemas.FieldEmployeeEmail]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeeEmail+" = ?", data)
	// }

	// employee_role
	// if data, ok := conditions[schemas.FieldEmployeeRole]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeeRole+" = ?", data)
	// }

	// employee_status
	// if data, ok := conditions[schemas.FieldEmployeeStatus]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldEmployeeStatus+" = ?", data)
	// }

	// inviter_record_id
	// if data, ok := conditions[schemas.FieldInviterRecordId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldInviterRecordId+" = ?", data)
	// }

	// inviter_user_id
	// if data, ok := conditions[schemas.FieldInviterUserId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldInviterUserId+" = ?", data)
	// }

	return dbConn
}

// UpdateColumns update columns
func (s *orgEmployeeRepo) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// id
	//if data, ok := conditions[schemas.FieldId]; ok {
	//	updateColumns[schemas.FieldId] = data
	//}

	// created_time
	//if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	//	updateColumns[schemas.FieldCreatedTime] = data
	//}

	// updated_time
	//if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	//	updateColumns[schemas.FieldUpdatedTime] = data
	//}

	// deleted_time
	//if data, ok := conditions[schemas.FieldDeletedTime]; ok {
	//	updateColumns[schemas.FieldDeletedTime] = data
	//}

	// employee_id
	//if data, ok := conditions[schemas.FieldEmployeeId]; ok {
	//	updateColumns[schemas.FieldEmployeeId] = data
	//}

	// user_id
	//if data, ok := conditions[schemas.FieldUserId]; ok {
	//	updateColumns[schemas.FieldUserId] = data
	//}

	// org_id
	//if data, ok := conditions[schemas.FieldOrgId]; ok {
	//	updateColumns[schemas.FieldOrgId] = data
	//}

	// employee_name
	//if data, ok := conditions[schemas.FieldEmployeeName]; ok {
	//	updateColumns[schemas.FieldEmployeeName] = data
	//}

	// employee_avatar
	//if data, ok := conditions[schemas.FieldEmployeeAvatar]; ok {
	//	updateColumns[schemas.FieldEmployeeAvatar] = data
	//}

	// employee_phone
	//if data, ok := conditions[schemas.FieldEmployeePhone]; ok {
	//	updateColumns[schemas.FieldEmployeePhone] = data
	//}

	// employee_email
	//if data, ok := conditions[schemas.FieldEmployeeEmail]; ok {
	//	updateColumns[schemas.FieldEmployeeEmail] = data
	//}

	// employee_role
	//if data, ok := conditions[schemas.FieldEmployeeRole]; ok {
	//	updateColumns[schemas.FieldEmployeeRole] = data
	//}

	// employee_status
	//if data, ok := conditions[schemas.FieldEmployeeStatus]; ok {
	//	updateColumns[schemas.FieldEmployeeStatus] = data
	//}

	// inviter_record_id
	//if data, ok := conditions[schemas.FieldInviterRecordId]; ok {
	//	updateColumns[schemas.FieldInviterRecordId] = data
	//}

	// inviter_user_id
	//if data, ok := conditions[schemas.FieldInviterUserId]; ok {
	//	updateColumns[schemas.FieldInviterUserId] = data
	//}

	return updateColumns
}
