// Package data
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package data

import (
	"bytes"
	context "context"
	"github.com/go-micro-saas/organization-service/app/org-service/internal/data/po"
	datarepos "github.com/go-micro-saas/organization-service/app/org-service/internal/data/repo"
	schemas "github.com/go-micro-saas/organization-service/app/org-service/internal/data/schema/org_record_for_user"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
	errorpkg "github.com/ikaiguang/go-srv-kit/kratos/error"
	gorm "gorm.io/gorm"
	"strings"
)

// orgRecordForUserRepo repo
type orgRecordForUserRepo struct {
	dbConn                 *gorm.DB                 // *gorm.DB
	OrgRecordForUserSchema schemas.OrgRecordForUser // OrgRecordForUser
}

// NewOrgRecordForUserRepo new data repo
func NewOrgRecordForUserRepo(dbConn *gorm.DB) datarepos.OrgRecordForUserRepo {
	return &orgRecordForUserRepo{
		dbConn: dbConn,
	}
}

// =============== 创建 ===============

// create insert one
func (s *orgRecordForUserRepo) create(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		Create(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Create insert one
func (s *orgRecordForUserRepo) Create(ctx context.Context, dataModel *po.OrgRecordForUser) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *orgRecordForUserRepo) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) error {
	return s.create(ctx, dbConn, dataModel)
}

// existCreate exist create
func (s *orgRecordForUserRepo) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (anotherModel *po.OrgRecordForUser, isNotFound bool, err error) {
	anotherModel = new(po.OrgRecordForUser)
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		Where(schemas.FieldUserId+" = ?", dataModel.UserId).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *orgRecordForUserRepo) ExistCreate(ctx context.Context, dataModel *po.OrgRecordForUser) (anotherModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

// ExistCreateWithDBConn exist create
func (s *orgRecordForUserRepo) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (anotherModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *orgRecordForUserRepo) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*po.OrgRecordForUser, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// CreateInBatches create many
func (s *orgRecordForUserRepo) CreateInBatches(ctx context.Context, dataModels []*po.OrgRecordForUser, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *orgRecordForUserRepo) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.OrgRecordForUser, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *orgRecordForUserRepo) update(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		// Where(schemas.FieldId+" = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Update update
func (s *orgRecordForUserRepo) Update(ctx context.Context, dataModel *po.OrgRecordForUser) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *orgRecordForUserRepo) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) error {
	return s.update(ctx, dbConn, dataModel)
}

// existUpdate exist update
func (s *orgRecordForUserRepo) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (anotherModel *po.OrgRecordForUser, isNotFound bool, err error) {
	anotherModel = new(po.OrgRecordForUser)
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *orgRecordForUserRepo) ExistUpdate(ctx context.Context, dataModel *po.OrgRecordForUser) (anotherModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *orgRecordForUserRepo) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (anotherModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

// =============== query one : 查一个 ===============

func (s *orgRecordForUserRepo) queryOneByUserId(ctx context.Context, dbConn *gorm.DB, userID uint64) (dataModel *po.OrgRecordForUser, isNotFound bool, err error) {
	dataModel = new(po.OrgRecordForUser)
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		Where(schemas.FieldUserId+" = ?", userID).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

func (s *orgRecordForUserRepo) QueryOneByUserId(ctx context.Context, userID uint64) (dataModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.queryOneByUserId(ctx, s.dbConn, userID)
}

func (s *orgRecordForUserRepo) QueryOneByUserIdWithDBConn(ctx context.Context, dbConn *gorm.DB, userID uint64) (dataModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.queryOneByUserId(ctx, dbConn, userID)
}

// queryOneByConditions query one by conditions
func (s *orgRecordForUserRepo) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.OrgRecordForUser, isNotFound bool, err error) {
	dataModel = new(po.OrgRecordForUser)
	dbConn = dbConn.WithContext(ctx).Table(s.OrgRecordForUserSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *orgRecordForUserRepo) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *orgRecordForUserRepo) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.OrgRecordForUser, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *orgRecordForUserRepo) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*po.OrgRecordForUser, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.OrgRecordForUserSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *orgRecordForUserRepo) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*po.OrgRecordForUser, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *orgRecordForUserRepo) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*po.OrgRecordForUser, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *orgRecordForUserRepo) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.OrgRecordForUser, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.OrgRecordForUserSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormpkg.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormpkg.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormpkg.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// List 列表
func (s *orgRecordForUserRepo) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.OrgRecordForUser, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *orgRecordForUserRepo) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.OrgRecordForUser, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

// =============== delete : 删除 ===============

// delete delete one
func (s *orgRecordForUserRepo) delete(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		Where(schemas.FieldUserId+" = ?", dataModel.UserId).
		Delete(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// Delete delete one
func (s *orgRecordForUserRepo) Delete(ctx context.Context, dataModel *po.OrgRecordForUser) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *orgRecordForUserRepo) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.OrgRecordForUser) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *orgRecordForUserRepo) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgRecordForUserSchema.TableName()).
		Where(schemas.FieldUserId+" in (?)", ids).
		Delete(po.OrgRecordForUser{}).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *orgRecordForUserRepo) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *orgRecordForUserRepo) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormpkg.BatchInsertRepo = new(OrgRecordForUserSlice)

// OrgRecordForUserSlice 表切片
type OrgRecordForUserSlice []*po.OrgRecordForUser

// TableName 表名
func (s *OrgRecordForUserSlice) TableName() string {
	return schemas.OrgRecordForUserSchema.TableName()
}

// Len 长度
func (s *OrgRecordForUserSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *OrgRecordForUserSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime, schemas.FieldUpdatedTime,
		schemas.FieldPersonalOrgId, schemas.FieldLastOrgId,
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *OrgRecordForUserSlice) InsertValues(args *gormpkg.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].PersonalOrgId)
		prepareData = append(prepareData, dataModels[index].LastOrgId)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *OrgRecordForUserSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime + "=excluded." + schemas.FieldCreatedTime,
		schemas.FieldUpdatedTime + "=excluded." + schemas.FieldUpdatedTime,
		schemas.FieldPersonalOrgId + "=excluded." + schemas.FieldPersonalOrgId,
		schemas.FieldLastOrgId + "=excluded." + schemas.FieldLastOrgId,
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *OrgRecordForUserSlice) ConflictActionForMySQL() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *OrgRecordForUserSlice) ConflictActionForPostgres() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *orgRecordForUserRepo) insert(ctx context.Context, dbConn *gorm.DB, dataModels OrgRecordForUserSlice) error {
	err := gormpkg.BatchInsertWithContext(ctx, dbConn, &dataModels)
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return nil
}

// Insert 批量插入
func (s *orgRecordForUserRepo) Insert(ctx context.Context, dataModels []*po.OrgRecordForUser) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *orgRecordForUserRepo) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.OrgRecordForUser) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *orgRecordForUserRepo) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	// tableName := s.OrgRecordForUserSchema.TableName()

	// On-demand loading

	// user_id
	// if data, ok := conditions[schemas.FieldUserId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserId+" = ?", data)
	// }

	// created_time
	// if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldCreatedTime+" = ?", data)
	// }

	// updated_time
	// if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUpdatedTime+" = ?", data)
	// }

	// personal_org_id
	// if data, ok := conditions[schemas.FieldPersonalOrgId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldPersonalOrgId+" = ?", data)
	// }

	// last_org_id
	// if data, ok := conditions[schemas.FieldLastOrgId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldLastOrgId+" = ?", data)
	// }

	return dbConn
}

// UpdateColumns update columns
func (s *orgRecordForUserRepo) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// user_id
	//if data, ok := conditions[schemas.FieldUserId]; ok {
	//	updateColumns[schemas.FieldUserId] = data
	//}

	// created_time
	//if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	//	updateColumns[schemas.FieldCreatedTime] = data
	//}

	// updated_time
	//if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	//	updateColumns[schemas.FieldUpdatedTime] = data
	//}

	// personal_org_id
	//if data, ok := conditions[schemas.FieldPersonalOrgId]; ok {
	//	updateColumns[schemas.FieldPersonalOrgId] = data
	//}

	// last_org_id
	//if data, ok := conditions[schemas.FieldLastOrgId]; ok {
	//	updateColumns[schemas.FieldLastOrgId] = data
	//}

	return updateColumns
}
