// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/org-service/v1/resources/org.resource.v1.proto

package resourcev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	enumv1 "github.com/go-micro-saas/organization-service/api/org-service/v1/enums"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = enumv1.OrgTypeEnum_OrgType(0)
)

// Validate checks the field values on PingReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PingReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PingReqMultiError, or nil if none found.
func (m *PingReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PingReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return PingReqMultiError(errors)
	}

	return nil
}

// PingReqMultiError is an error wrapping multiple validation errors returned
// by PingReq.ValidateAll() if the designated constraints aren't met.
type PingReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingReqMultiError) AllErrors() []error { return m }

// PingReqValidationError is the validation error returned by PingReq.Validate
// if the designated constraints aren't met.
type PingReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingReqValidationError) ErrorName() string { return "PingReqValidationError" }

// Error satisfies the builtin error interface
func (e PingReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingReqValidationError{}

// Validate checks the field values on PingResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PingResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PingRespMultiError, or nil
// if none found.
func (m *PingResp) ValidateAll() error {
	return m.validate(true)
}

func (m *PingResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PingRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PingRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PingRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PingRespMultiError(errors)
	}

	return nil
}

// PingRespMultiError is an error wrapping multiple validation errors returned
// by PingResp.ValidateAll() if the designated constraints aren't met.
type PingRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingRespMultiError) AllErrors() []error { return m }

// PingRespValidationError is the validation error returned by
// PingResp.Validate if the designated constraints aren't met.
type PingRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingRespValidationError) ErrorName() string { return "PingRespValidationError" }

// Error satisfies the builtin error interface
func (e PingRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingRespValidationError{}

// Validate checks the field values on PingRespData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PingRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingRespData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PingRespDataMultiError, or
// nil if none found.
func (m *PingRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *PingRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return PingRespDataMultiError(errors)
	}

	return nil
}

// PingRespDataMultiError is an error wrapping multiple validation errors
// returned by PingRespData.ValidateAll() if the designated constraints aren't met.
type PingRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingRespDataMultiError) AllErrors() []error { return m }

// PingRespDataValidationError is the validation error returned by
// PingRespData.Validate if the designated constraints aren't met.
type PingRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingRespDataValidationError) ErrorName() string { return "PingRespDataValidationError" }

// Error satisfies the builtin error interface
func (e PingRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingRespDataValidationError{}

// Validate checks the field values on Org with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Org) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Org with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OrgMultiError, or nil if none found.
func (m *Org) ValidateAll() error {
	return m.validate(true)
}

func (m *Org) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreatedTime

	// no validation rules for UpdatedTime

	// no validation rules for DeletedTime

	// no validation rules for OrgId

	// no validation rules for OrgName

	// no validation rules for OrgAvatar

	// no validation rules for OrgContactName

	// no validation rules for OrgContactPhone

	// no validation rules for OrgContactEmail

	// no validation rules for OrgType

	// no validation rules for OrgStatus

	// no validation rules for OrgIndustryId

	// no validation rules for OrgScaleId

	// no validation rules for OrgAddress

	// no validation rules for OrgZipCode

	// no validation rules for OrgCreatorId

	if len(errors) > 0 {
		return OrgMultiError(errors)
	}

	return nil
}

// OrgMultiError is an error wrapping multiple validation errors returned by
// Org.ValidateAll() if the designated constraints aren't met.
type OrgMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgMultiError) AllErrors() []error { return m }

// OrgValidationError is the validation error returned by Org.Validate if the
// designated constraints aren't met.
type OrgValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgValidationError) ErrorName() string { return "OrgValidationError" }

// Error satisfies the builtin error interface
func (e OrgValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrg.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgValidationError{}

// Validate checks the field values on CreateOrgReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateOrgReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrgReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateOrgReqMultiError, or
// nil if none found.
func (m *CreateOrgReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrgReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetCreatorId() <= 0 {
		err := CreateOrgReqValidationError{
			field:  "CreatorId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCreatorName()) < 1 {
		err := CreateOrgReqValidationError{
			field:  "CreatorName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatorAvatar() != "" {

	}

	if utf8.RuneCountInString(m.GetOrgName()) < 1 {
		err := CreateOrgReqValidationError{
			field:  "OrgName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgAvatar() != "" {

	}

	if _, ok := _CreateOrgReq_OrgType_NotInLookup[m.GetOrgType()]; ok {
		err := CreateOrgReqValidationError{
			field:  "OrgType",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateOrgReqMultiError(errors)
	}

	return nil
}

// CreateOrgReqMultiError is an error wrapping multiple validation errors
// returned by CreateOrgReq.ValidateAll() if the designated constraints aren't met.
type CreateOrgReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrgReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrgReqMultiError) AllErrors() []error { return m }

// CreateOrgReqValidationError is the validation error returned by
// CreateOrgReq.Validate if the designated constraints aren't met.
type CreateOrgReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrgReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrgReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrgReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrgReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrgReqValidationError) ErrorName() string { return "CreateOrgReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateOrgReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrgReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrgReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrgReqValidationError{}

var _CreateOrgReq_OrgType_NotInLookup = map[enumv1.OrgTypeEnum_OrgType]struct{}{
	0: {},
}

// Validate checks the field values on OnlyCreateOrgReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OnlyCreateOrgReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnlyCreateOrgReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnlyCreateOrgReqMultiError, or nil if none found.
func (m *OnlyCreateOrgReq) ValidateAll() error {
	return m.validate(true)
}

func (m *OnlyCreateOrgReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetCreatorId() <= 0 {
		err := OnlyCreateOrgReqValidationError{
			field:  "CreatorId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrgName()) < 1 {
		err := OnlyCreateOrgReqValidationError{
			field:  "OrgName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgAvatar() != "" {

	}

	if _, ok := _OnlyCreateOrgReq_OrgType_NotInLookup[m.GetOrgType()]; ok {
		err := OnlyCreateOrgReqValidationError{
			field:  "OrgType",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OnlyCreateOrgReqMultiError(errors)
	}

	return nil
}

// OnlyCreateOrgReqMultiError is an error wrapping multiple validation errors
// returned by OnlyCreateOrgReq.ValidateAll() if the designated constraints
// aren't met.
type OnlyCreateOrgReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnlyCreateOrgReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnlyCreateOrgReqMultiError) AllErrors() []error { return m }

// OnlyCreateOrgReqValidationError is the validation error returned by
// OnlyCreateOrgReq.Validate if the designated constraints aren't met.
type OnlyCreateOrgReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnlyCreateOrgReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnlyCreateOrgReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnlyCreateOrgReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnlyCreateOrgReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnlyCreateOrgReqValidationError) ErrorName() string { return "OnlyCreateOrgReqValidationError" }

// Error satisfies the builtin error interface
func (e OnlyCreateOrgReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnlyCreateOrgReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnlyCreateOrgReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnlyCreateOrgReqValidationError{}

var _OnlyCreateOrgReq_OrgType_NotInLookup = map[enumv1.OrgTypeEnum_OrgType]struct{}{
	0: {},
}

// Validate checks the field values on CreateOrgResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateOrgResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrgResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateOrgRespMultiError, or
// nil if none found.
func (m *CreateOrgResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrgResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateOrgRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateOrgRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateOrgRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateOrgRespMultiError(errors)
	}

	return nil
}

// CreateOrgRespMultiError is an error wrapping multiple validation errors
// returned by CreateOrgResp.ValidateAll() if the designated constraints
// aren't met.
type CreateOrgRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrgRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrgRespMultiError) AllErrors() []error { return m }

// CreateOrgRespValidationError is the validation error returned by
// CreateOrgResp.Validate if the designated constraints aren't met.
type CreateOrgRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrgRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrgRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrgRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrgRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrgRespValidationError) ErrorName() string { return "CreateOrgRespValidationError" }

// Error satisfies the builtin error interface
func (e CreateOrgRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrgResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrgRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrgRespValidationError{}

// Validate checks the field values on CreateOrgRespData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateOrgRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrgRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateOrgRespDataMultiError, or nil if none found.
func (m *CreateOrgRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrgRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrgId

	// no validation rules for OrgName

	// no validation rules for OrgAvatar

	// no validation rules for OrgType

	if len(errors) > 0 {
		return CreateOrgRespDataMultiError(errors)
	}

	return nil
}

// CreateOrgRespDataMultiError is an error wrapping multiple validation errors
// returned by CreateOrgRespData.ValidateAll() if the designated constraints
// aren't met.
type CreateOrgRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrgRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrgRespDataMultiError) AllErrors() []error { return m }

// CreateOrgRespDataValidationError is the validation error returned by
// CreateOrgRespData.Validate if the designated constraints aren't met.
type CreateOrgRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrgRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrgRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrgRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrgRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrgRespDataValidationError) ErrorName() string {
	return "CreateOrgRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOrgRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrgRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrgRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrgRespDataValidationError{}

// Validate checks the field values on AddEmployeeReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddEmployeeReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddEmployeeReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddEmployeeReqMultiError,
// or nil if none found.
func (m *AddEmployeeReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddEmployeeReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOperatorUid() <= 0 {
		err := AddEmployeeReqValidationError{
			field:  "OperatorUid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgId() <= 0 {
		err := AddEmployeeReqValidationError{
			field:  "OrgId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := AddEmployeeReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserName()) < 1 {
		err := AddEmployeeReqValidationError{
			field:  "UserName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AddEmployeeReq_EmployeeRole_NotInLookup[m.GetEmployeeRole()]; ok {
		err := AddEmployeeReqValidationError{
			field:  "EmployeeRole",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserAvatar() != "" {

	}

	if m.GetUserPhone() != "" {

	}

	if m.GetUserEmail() != "" {

	}

	if len(errors) > 0 {
		return AddEmployeeReqMultiError(errors)
	}

	return nil
}

// AddEmployeeReqMultiError is an error wrapping multiple validation errors
// returned by AddEmployeeReq.ValidateAll() if the designated constraints
// aren't met.
type AddEmployeeReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddEmployeeReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddEmployeeReqMultiError) AllErrors() []error { return m }

// AddEmployeeReqValidationError is the validation error returned by
// AddEmployeeReq.Validate if the designated constraints aren't met.
type AddEmployeeReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddEmployeeReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddEmployeeReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddEmployeeReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddEmployeeReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddEmployeeReqValidationError) ErrorName() string { return "AddEmployeeReqValidationError" }

// Error satisfies the builtin error interface
func (e AddEmployeeReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddEmployeeReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddEmployeeReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddEmployeeReqValidationError{}

var _AddEmployeeReq_EmployeeRole_NotInLookup = map[enumv1.OrgEmployeeRoleEnum_OrgEmployeeRole]struct{}{
	0: {},
}

// Validate checks the field values on AddEmployeeResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddEmployeeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddEmployeeResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddEmployeeRespMultiError, or nil if none found.
func (m *AddEmployeeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AddEmployeeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddEmployeeRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddEmployeeRespMultiError(errors)
	}

	return nil
}

// AddEmployeeRespMultiError is an error wrapping multiple validation errors
// returned by AddEmployeeResp.ValidateAll() if the designated constraints
// aren't met.
type AddEmployeeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddEmployeeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddEmployeeRespMultiError) AllErrors() []error { return m }

// AddEmployeeRespValidationError is the validation error returned by
// AddEmployeeResp.Validate if the designated constraints aren't met.
type AddEmployeeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddEmployeeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddEmployeeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddEmployeeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddEmployeeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddEmployeeRespValidationError) ErrorName() string { return "AddEmployeeRespValidationError" }

// Error satisfies the builtin error interface
func (e AddEmployeeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddEmployeeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddEmployeeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddEmployeeRespValidationError{}

// Validate checks the field values on AddEmployeeRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddEmployeeRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddEmployeeRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddEmployeeRespDataMultiError, or nil if none found.
func (m *AddEmployeeRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *AddEmployeeRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrgId

	// no validation rules for UserId

	// no validation rules for EmployeeId

	// no validation rules for EmployeeName

	// no validation rules for EmployeeAvatar

	// no validation rules for EmployeeStatus

	// no validation rules for EmployeeRole

	if len(errors) > 0 {
		return AddEmployeeRespDataMultiError(errors)
	}

	return nil
}

// AddEmployeeRespDataMultiError is an error wrapping multiple validation
// errors returned by AddEmployeeRespData.ValidateAll() if the designated
// constraints aren't met.
type AddEmployeeRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddEmployeeRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddEmployeeRespDataMultiError) AllErrors() []error { return m }

// AddEmployeeRespDataValidationError is the validation error returned by
// AddEmployeeRespData.Validate if the designated constraints aren't met.
type AddEmployeeRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddEmployeeRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddEmployeeRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddEmployeeRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddEmployeeRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddEmployeeRespDataValidationError) ErrorName() string {
	return "AddEmployeeRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e AddEmployeeRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddEmployeeRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddEmployeeRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddEmployeeRespDataValidationError{}

// Validate checks the field values on GenerateInviteLinkReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateInviteLinkReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateInviteLinkReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateInviteLinkReqMultiError, or nil if none found.
func (m *GenerateInviteLinkReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateInviteLinkReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOperatorUid() <= 0 {
		err := GenerateInviteLinkReqValidationError{
			field:  "OperatorUid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgId() <= 0 {
		err := GenerateInviteLinkReqValidationError{
			field:  "OrgId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GenerateInviteLinkReqMultiError(errors)
	}

	return nil
}

// GenerateInviteLinkReqMultiError is an error wrapping multiple validation
// errors returned by GenerateInviteLinkReq.ValidateAll() if the designated
// constraints aren't met.
type GenerateInviteLinkReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateInviteLinkReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateInviteLinkReqMultiError) AllErrors() []error { return m }

// GenerateInviteLinkReqValidationError is the validation error returned by
// GenerateInviteLinkReq.Validate if the designated constraints aren't met.
type GenerateInviteLinkReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateInviteLinkReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateInviteLinkReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateInviteLinkReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateInviteLinkReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateInviteLinkReqValidationError) ErrorName() string {
	return "GenerateInviteLinkReqValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateInviteLinkReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateInviteLinkReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateInviteLinkReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateInviteLinkReqValidationError{}

// Validate checks the field values on GenerateInviteLinkResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateInviteLinkResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateInviteLinkResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateInviteLinkRespMultiError, or nil if none found.
func (m *GenerateInviteLinkResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateInviteLinkResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateInviteLinkRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateInviteLinkRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateInviteLinkRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GenerateInviteLinkRespMultiError(errors)
	}

	return nil
}

// GenerateInviteLinkRespMultiError is an error wrapping multiple validation
// errors returned by GenerateInviteLinkResp.ValidateAll() if the designated
// constraints aren't met.
type GenerateInviteLinkRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateInviteLinkRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateInviteLinkRespMultiError) AllErrors() []error { return m }

// GenerateInviteLinkRespValidationError is the validation error returned by
// GenerateInviteLinkResp.Validate if the designated constraints aren't met.
type GenerateInviteLinkRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateInviteLinkRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateInviteLinkRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateInviteLinkRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateInviteLinkRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateInviteLinkRespValidationError) ErrorName() string {
	return "GenerateInviteLinkRespValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateInviteLinkRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateInviteLinkResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateInviteLinkRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateInviteLinkRespValidationError{}

// Validate checks the field values on GenerateInviteLinkRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateInviteLinkRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateInviteLinkRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateInviteLinkRespDataMultiError, or nil if none found.
func (m *GenerateInviteLinkRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateInviteLinkRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InviteId

	// no validation rules for InviteCode

	if all {
		switch v := interface{}(m.GetExpireTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateInviteLinkRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateInviteLinkRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateInviteLinkRespDataValidationError{
				field:  "ExpireTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GenerateInviteLinkRespDataMultiError(errors)
	}

	return nil
}

// GenerateInviteLinkRespDataMultiError is an error wrapping multiple
// validation errors returned by GenerateInviteLinkRespData.ValidateAll() if
// the designated constraints aren't met.
type GenerateInviteLinkRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateInviteLinkRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateInviteLinkRespDataMultiError) AllErrors() []error { return m }

// GenerateInviteLinkRespDataValidationError is the validation error returned
// by GenerateInviteLinkRespData.Validate if the designated constraints aren't met.
type GenerateInviteLinkRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateInviteLinkRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateInviteLinkRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateInviteLinkRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateInviteLinkRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateInviteLinkRespDataValidationError) ErrorName() string {
	return "GenerateInviteLinkRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateInviteLinkRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateInviteLinkRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateInviteLinkRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateInviteLinkRespDataValidationError{}

// Validate checks the field values on CreateInviteEmployeeReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInviteEmployeeReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteEmployeeReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInviteEmployeeReqMultiError, or nil if none found.
func (m *CreateInviteEmployeeReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteEmployeeReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOperatorUid() <= 0 {
		err := CreateInviteEmployeeReqValidationError{
			field:  "OperatorUid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgId() <= 0 {
		err := CreateInviteEmployeeReqValidationError{
			field:  "OrgId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInviteUserId() <= 0 {
		err := CreateInviteEmployeeReqValidationError{
			field:  "InviteUserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetInviteAccount()) < 1 {
		err := CreateInviteEmployeeReqValidationError{
			field:  "InviteAccount",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetExpireTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteEmployeeReqValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteEmployeeReqValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteEmployeeReqValidationError{
				field:  "ExpireTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if _, ok := _CreateInviteEmployeeReq_InviteAccountType_NotInLookup[m.GetInviteAccountType()]; ok {
		err := CreateInviteEmployeeReqValidationError{
			field:  "InviteAccountType",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateInviteEmployeeReq_InviteEmployeeRole_NotInLookup[m.GetInviteEmployeeRole()]; ok {
		err := CreateInviteEmployeeReqValidationError{
			field:  "InviteEmployeeRole",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateInviteEmployeeReqMultiError(errors)
	}

	return nil
}

// CreateInviteEmployeeReqMultiError is an error wrapping multiple validation
// errors returned by CreateInviteEmployeeReq.ValidateAll() if the designated
// constraints aren't met.
type CreateInviteEmployeeReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteEmployeeReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteEmployeeReqMultiError) AllErrors() []error { return m }

// CreateInviteEmployeeReqValidationError is the validation error returned by
// CreateInviteEmployeeReq.Validate if the designated constraints aren't met.
type CreateInviteEmployeeReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteEmployeeReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteEmployeeReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteEmployeeReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteEmployeeReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteEmployeeReqValidationError) ErrorName() string {
	return "CreateInviteEmployeeReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteEmployeeReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteEmployeeReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteEmployeeReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteEmployeeReqValidationError{}

var _CreateInviteEmployeeReq_InviteAccountType_NotInLookup = map[enumv1.OrgInviteAccountTypeEnum_OrgInviteAccountType]struct{}{
	0: {},
}

var _CreateInviteEmployeeReq_InviteEmployeeRole_NotInLookup = map[enumv1.OrgEmployeeRoleEnum_OrgEmployeeRole]struct{}{
	0: {},
}

// Validate checks the field values on CreateInviteEmployeeResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInviteEmployeeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteEmployeeResp with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInviteEmployeeRespMultiError, or nil if none found.
func (m *CreateInviteEmployeeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteEmployeeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteEmployeeRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInviteEmployeeRespMultiError(errors)
	}

	return nil
}

// CreateInviteEmployeeRespMultiError is an error wrapping multiple validation
// errors returned by CreateInviteEmployeeResp.ValidateAll() if the designated
// constraints aren't met.
type CreateInviteEmployeeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteEmployeeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteEmployeeRespMultiError) AllErrors() []error { return m }

// CreateInviteEmployeeRespValidationError is the validation error returned by
// CreateInviteEmployeeResp.Validate if the designated constraints aren't met.
type CreateInviteEmployeeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteEmployeeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteEmployeeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteEmployeeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteEmployeeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteEmployeeRespValidationError) ErrorName() string {
	return "CreateInviteEmployeeRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteEmployeeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteEmployeeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteEmployeeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteEmployeeRespValidationError{}

// Validate checks the field values on CreateInviteEmployeeRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInviteEmployeeRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteEmployeeRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInviteEmployeeRespDataMultiError, or nil if none found.
func (m *CreateInviteEmployeeRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteEmployeeRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InviteId

	// no validation rules for InviteCode

	if all {
		switch v := interface{}(m.GetExpireTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteEmployeeRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteEmployeeRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteEmployeeRespDataValidationError{
				field:  "ExpireTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AssignEmployeeId

	if len(errors) > 0 {
		return CreateInviteEmployeeRespDataMultiError(errors)
	}

	return nil
}

// CreateInviteEmployeeRespDataMultiError is an error wrapping multiple
// validation errors returned by CreateInviteEmployeeRespData.ValidateAll() if
// the designated constraints aren't met.
type CreateInviteEmployeeRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteEmployeeRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteEmployeeRespDataMultiError) AllErrors() []error { return m }

// CreateInviteEmployeeRespDataValidationError is the validation error returned
// by CreateInviteEmployeeRespData.Validate if the designated constraints
// aren't met.
type CreateInviteEmployeeRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteEmployeeRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteEmployeeRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteEmployeeRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteEmployeeRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteEmployeeRespDataValidationError) ErrorName() string {
	return "CreateInviteEmployeeRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteEmployeeRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteEmployeeRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteEmployeeRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteEmployeeRespDataValidationError{}
