// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/org-service/v1/resources/org.resource.v1.proto

package resourcev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	enumv1 "github.com/go-micro-saas/organization-service/api/org-service/v1/enums"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = enumv1.OrgTypeEnum_OrgType(0)
)

// Validate checks the field values on PingReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PingReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PingReqMultiError, or nil if none found.
func (m *PingReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PingReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return PingReqMultiError(errors)
	}

	return nil
}

// PingReqMultiError is an error wrapping multiple validation errors returned
// by PingReq.ValidateAll() if the designated constraints aren't met.
type PingReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingReqMultiError) AllErrors() []error { return m }

// PingReqValidationError is the validation error returned by PingReq.Validate
// if the designated constraints aren't met.
type PingReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingReqValidationError) ErrorName() string { return "PingReqValidationError" }

// Error satisfies the builtin error interface
func (e PingReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingReqValidationError{}

// Validate checks the field values on PingResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PingResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PingRespMultiError, or nil
// if none found.
func (m *PingResp) ValidateAll() error {
	return m.validate(true)
}

func (m *PingResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PingRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PingRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PingRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PingRespMultiError(errors)
	}

	return nil
}

// PingRespMultiError is an error wrapping multiple validation errors returned
// by PingResp.ValidateAll() if the designated constraints aren't met.
type PingRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingRespMultiError) AllErrors() []error { return m }

// PingRespValidationError is the validation error returned by
// PingResp.Validate if the designated constraints aren't met.
type PingRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingRespValidationError) ErrorName() string { return "PingRespValidationError" }

// Error satisfies the builtin error interface
func (e PingRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingRespValidationError{}

// Validate checks the field values on PingRespData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PingRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PingRespData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PingRespDataMultiError, or
// nil if none found.
func (m *PingRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *PingRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return PingRespDataMultiError(errors)
	}

	return nil
}

// PingRespDataMultiError is an error wrapping multiple validation errors
// returned by PingRespData.ValidateAll() if the designated constraints aren't met.
type PingRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PingRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PingRespDataMultiError) AllErrors() []error { return m }

// PingRespDataValidationError is the validation error returned by
// PingRespData.Validate if the designated constraints aren't met.
type PingRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingRespDataValidationError) ErrorName() string { return "PingRespDataValidationError" }

// Error satisfies the builtin error interface
func (e PingRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingRespDataValidationError{}

// Validate checks the field values on Org with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Org) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Org with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OrgMultiError, or nil if none found.
func (m *Org) ValidateAll() error {
	return m.validate(true)
}

func (m *Org) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreatedTime

	// no validation rules for UpdatedTime

	// no validation rules for DeletedTime

	// no validation rules for OrgId

	// no validation rules for OrgName

	// no validation rules for OrgAvatar

	// no validation rules for OrgContactName

	// no validation rules for OrgContactPhone

	// no validation rules for OrgContactEmail

	// no validation rules for OrgType

	// no validation rules for OrgStatus

	// no validation rules for OrgIndustryId

	// no validation rules for OrgScaleId

	// no validation rules for OrgAddress

	// no validation rules for OrgZipCode

	// no validation rules for OrgCreatorId

	if len(errors) > 0 {
		return OrgMultiError(errors)
	}

	return nil
}

// OrgMultiError is an error wrapping multiple validation errors returned by
// Org.ValidateAll() if the designated constraints aren't met.
type OrgMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgMultiError) AllErrors() []error { return m }

// OrgValidationError is the validation error returned by Org.Validate if the
// designated constraints aren't met.
type OrgValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgValidationError) ErrorName() string { return "OrgValidationError" }

// Error satisfies the builtin error interface
func (e OrgValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrg.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgValidationError{}

// Validate checks the field values on CreateOrgReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateOrgReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrgReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateOrgReqMultiError, or
// nil if none found.
func (m *CreateOrgReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrgReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetCreatorId() <= 0 {
		err := CreateOrgReqValidationError{
			field:  "CreatorId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCreatorName()) < 1 {
		err := CreateOrgReqValidationError{
			field:  "CreatorName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatorAvatar() != "" {

	}

	if utf8.RuneCountInString(m.GetOrgName()) < 1 {
		err := CreateOrgReqValidationError{
			field:  "OrgName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgAvatar() != "" {

	}

	if _, ok := _CreateOrgReq_OrgType_NotInLookup[m.GetOrgType()]; ok {
		err := CreateOrgReqValidationError{
			field:  "OrgType",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateOrgReqMultiError(errors)
	}

	return nil
}

// CreateOrgReqMultiError is an error wrapping multiple validation errors
// returned by CreateOrgReq.ValidateAll() if the designated constraints aren't met.
type CreateOrgReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrgReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrgReqMultiError) AllErrors() []error { return m }

// CreateOrgReqValidationError is the validation error returned by
// CreateOrgReq.Validate if the designated constraints aren't met.
type CreateOrgReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrgReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrgReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrgReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrgReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrgReqValidationError) ErrorName() string { return "CreateOrgReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateOrgReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrgReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrgReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrgReqValidationError{}

var _CreateOrgReq_OrgType_NotInLookup = map[enumv1.OrgTypeEnum_OrgType]struct{}{
	0: {},
}

// Validate checks the field values on OnlyCreateOrgReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OnlyCreateOrgReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnlyCreateOrgReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnlyCreateOrgReqMultiError, or nil if none found.
func (m *OnlyCreateOrgReq) ValidateAll() error {
	return m.validate(true)
}

func (m *OnlyCreateOrgReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetCreatorId() <= 0 {
		err := OnlyCreateOrgReqValidationError{
			field:  "CreatorId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrgName()) < 1 {
		err := OnlyCreateOrgReqValidationError{
			field:  "OrgName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgAvatar() != "" {

	}

	if _, ok := _OnlyCreateOrgReq_OrgType_NotInLookup[m.GetOrgType()]; ok {
		err := OnlyCreateOrgReqValidationError{
			field:  "OrgType",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OnlyCreateOrgReqMultiError(errors)
	}

	return nil
}

// OnlyCreateOrgReqMultiError is an error wrapping multiple validation errors
// returned by OnlyCreateOrgReq.ValidateAll() if the designated constraints
// aren't met.
type OnlyCreateOrgReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnlyCreateOrgReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnlyCreateOrgReqMultiError) AllErrors() []error { return m }

// OnlyCreateOrgReqValidationError is the validation error returned by
// OnlyCreateOrgReq.Validate if the designated constraints aren't met.
type OnlyCreateOrgReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnlyCreateOrgReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnlyCreateOrgReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnlyCreateOrgReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnlyCreateOrgReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnlyCreateOrgReqValidationError) ErrorName() string { return "OnlyCreateOrgReqValidationError" }

// Error satisfies the builtin error interface
func (e OnlyCreateOrgReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnlyCreateOrgReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnlyCreateOrgReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnlyCreateOrgReqValidationError{}

var _OnlyCreateOrgReq_OrgType_NotInLookup = map[enumv1.OrgTypeEnum_OrgType]struct{}{
	0: {},
}

// Validate checks the field values on CreateOrgResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateOrgResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrgResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateOrgRespMultiError, or
// nil if none found.
func (m *CreateOrgResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrgResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateOrgRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateOrgRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateOrgRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateOrgRespMultiError(errors)
	}

	return nil
}

// CreateOrgRespMultiError is an error wrapping multiple validation errors
// returned by CreateOrgResp.ValidateAll() if the designated constraints
// aren't met.
type CreateOrgRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrgRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrgRespMultiError) AllErrors() []error { return m }

// CreateOrgRespValidationError is the validation error returned by
// CreateOrgResp.Validate if the designated constraints aren't met.
type CreateOrgRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrgRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrgRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrgRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrgRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrgRespValidationError) ErrorName() string { return "CreateOrgRespValidationError" }

// Error satisfies the builtin error interface
func (e CreateOrgRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrgResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrgRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrgRespValidationError{}

// Validate checks the field values on CreateOrgRespData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateOrgRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrgRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateOrgRespDataMultiError, or nil if none found.
func (m *CreateOrgRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrgRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrgId

	// no validation rules for OrgName

	// no validation rules for OrgAvatar

	// no validation rules for OrgType

	if len(errors) > 0 {
		return CreateOrgRespDataMultiError(errors)
	}

	return nil
}

// CreateOrgRespDataMultiError is an error wrapping multiple validation errors
// returned by CreateOrgRespData.ValidateAll() if the designated constraints
// aren't met.
type CreateOrgRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrgRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrgRespDataMultiError) AllErrors() []error { return m }

// CreateOrgRespDataValidationError is the validation error returned by
// CreateOrgRespData.Validate if the designated constraints aren't met.
type CreateOrgRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrgRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrgRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrgRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrgRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrgRespDataValidationError) ErrorName() string {
	return "CreateOrgRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOrgRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrgRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrgRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrgRespDataValidationError{}

// Validate checks the field values on AddEmployeeReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddEmployeeReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddEmployeeReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddEmployeeReqMultiError,
// or nil if none found.
func (m *AddEmployeeReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddEmployeeReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOperatorUid() <= 0 {
		err := AddEmployeeReqValidationError{
			field:  "OperatorUid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgId() <= 0 {
		err := AddEmployeeReqValidationError{
			field:  "OrgId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := AddEmployeeReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserName()) < 1 {
		err := AddEmployeeReqValidationError{
			field:  "UserName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AddEmployeeReq_EmployeeRole_NotInLookup[m.GetEmployeeRole()]; ok {
		err := AddEmployeeReqValidationError{
			field:  "EmployeeRole",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserAvatar() != "" {

	}

	if m.GetUserPhone() != "" {

	}

	if m.GetUserEmail() != "" {

	}

	if len(errors) > 0 {
		return AddEmployeeReqMultiError(errors)
	}

	return nil
}

// AddEmployeeReqMultiError is an error wrapping multiple validation errors
// returned by AddEmployeeReq.ValidateAll() if the designated constraints
// aren't met.
type AddEmployeeReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddEmployeeReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddEmployeeReqMultiError) AllErrors() []error { return m }

// AddEmployeeReqValidationError is the validation error returned by
// AddEmployeeReq.Validate if the designated constraints aren't met.
type AddEmployeeReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddEmployeeReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddEmployeeReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddEmployeeReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddEmployeeReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddEmployeeReqValidationError) ErrorName() string { return "AddEmployeeReqValidationError" }

// Error satisfies the builtin error interface
func (e AddEmployeeReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddEmployeeReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddEmployeeReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddEmployeeReqValidationError{}

var _AddEmployeeReq_EmployeeRole_NotInLookup = map[enumv1.OrgEmployeeRoleEnum_OrgEmployeeRole]struct{}{
	0: {},
}

// Validate checks the field values on AddEmployeeResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddEmployeeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddEmployeeResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddEmployeeRespMultiError, or nil if none found.
func (m *AddEmployeeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AddEmployeeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddEmployeeRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddEmployeeRespMultiError(errors)
	}

	return nil
}

// AddEmployeeRespMultiError is an error wrapping multiple validation errors
// returned by AddEmployeeResp.ValidateAll() if the designated constraints
// aren't met.
type AddEmployeeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddEmployeeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddEmployeeRespMultiError) AllErrors() []error { return m }

// AddEmployeeRespValidationError is the validation error returned by
// AddEmployeeResp.Validate if the designated constraints aren't met.
type AddEmployeeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddEmployeeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddEmployeeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddEmployeeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddEmployeeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddEmployeeRespValidationError) ErrorName() string { return "AddEmployeeRespValidationError" }

// Error satisfies the builtin error interface
func (e AddEmployeeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddEmployeeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddEmployeeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddEmployeeRespValidationError{}

// Validate checks the field values on AddEmployeeRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddEmployeeRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddEmployeeRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddEmployeeRespDataMultiError, or nil if none found.
func (m *AddEmployeeRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *AddEmployeeRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrgId

	// no validation rules for UserId

	// no validation rules for EmployeeId

	// no validation rules for EmployeeName

	// no validation rules for EmployeeAvatar

	// no validation rules for EmployeeStatus

	// no validation rules for EmployeeRole

	if len(errors) > 0 {
		return AddEmployeeRespDataMultiError(errors)
	}

	return nil
}

// AddEmployeeRespDataMultiError is an error wrapping multiple validation
// errors returned by AddEmployeeRespData.ValidateAll() if the designated
// constraints aren't met.
type AddEmployeeRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddEmployeeRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddEmployeeRespDataMultiError) AllErrors() []error { return m }

// AddEmployeeRespDataValidationError is the validation error returned by
// AddEmployeeRespData.Validate if the designated constraints aren't met.
type AddEmployeeRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddEmployeeRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddEmployeeRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddEmployeeRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddEmployeeRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddEmployeeRespDataValidationError) ErrorName() string {
	return "AddEmployeeRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e AddEmployeeRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddEmployeeRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddEmployeeRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddEmployeeRespDataValidationError{}

// Validate checks the field values on CreateInviteRecordForLinkReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInviteRecordForLinkReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteRecordForLinkReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInviteRecordForLinkReqMultiError, or nil if none found.
func (m *CreateInviteRecordForLinkReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteRecordForLinkReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOperatorUid() <= 0 {
		err := CreateInviteRecordForLinkReqValidationError{
			field:  "OperatorUid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgId() <= 0 {
		err := CreateInviteRecordForLinkReqValidationError{
			field:  "OrgId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateInviteRecordForLinkReq_InviteEmployeeRole_NotInLookup[m.GetInviteEmployeeRole()]; ok {
		err := CreateInviteRecordForLinkReqValidationError{
			field:  "InviteEmployeeRole",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateInviteRecordForLinkReqMultiError(errors)
	}

	return nil
}

// CreateInviteRecordForLinkReqMultiError is an error wrapping multiple
// validation errors returned by CreateInviteRecordForLinkReq.ValidateAll() if
// the designated constraints aren't met.
type CreateInviteRecordForLinkReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteRecordForLinkReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteRecordForLinkReqMultiError) AllErrors() []error { return m }

// CreateInviteRecordForLinkReqValidationError is the validation error returned
// by CreateInviteRecordForLinkReq.Validate if the designated constraints
// aren't met.
type CreateInviteRecordForLinkReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteRecordForLinkReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteRecordForLinkReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteRecordForLinkReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteRecordForLinkReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteRecordForLinkReqValidationError) ErrorName() string {
	return "CreateInviteRecordForLinkReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteRecordForLinkReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteRecordForLinkReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteRecordForLinkReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteRecordForLinkReqValidationError{}

var _CreateInviteRecordForLinkReq_InviteEmployeeRole_NotInLookup = map[enumv1.OrgEmployeeRoleEnum_OrgEmployeeRole]struct{}{
	0: {},
}

// Validate checks the field values on CreateInviteRecordForLinkResp with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInviteRecordForLinkResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteRecordForLinkResp with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateInviteRecordForLinkRespMultiError, or nil if none found.
func (m *CreateInviteRecordForLinkResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteRecordForLinkResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteRecordForLinkRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteRecordForLinkRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteRecordForLinkRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInviteRecordForLinkRespMultiError(errors)
	}

	return nil
}

// CreateInviteRecordForLinkRespMultiError is an error wrapping multiple
// validation errors returned by CreateInviteRecordForLinkResp.ValidateAll()
// if the designated constraints aren't met.
type CreateInviteRecordForLinkRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteRecordForLinkRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteRecordForLinkRespMultiError) AllErrors() []error { return m }

// CreateInviteRecordForLinkRespValidationError is the validation error
// returned by CreateInviteRecordForLinkResp.Validate if the designated
// constraints aren't met.
type CreateInviteRecordForLinkRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteRecordForLinkRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteRecordForLinkRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteRecordForLinkRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteRecordForLinkRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteRecordForLinkRespValidationError) ErrorName() string {
	return "CreateInviteRecordForLinkRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteRecordForLinkRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteRecordForLinkResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteRecordForLinkRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteRecordForLinkRespValidationError{}

// Validate checks the field values on CreateInviteRecordForLinkRespData with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateInviteRecordForLinkRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteRecordForLinkRespData
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateInviteRecordForLinkRespDataMultiError, or nil if none found.
func (m *CreateInviteRecordForLinkRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteRecordForLinkRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InviteId

	// no validation rules for InviteCode

	if all {
		switch v := interface{}(m.GetExpireTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteRecordForLinkRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteRecordForLinkRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteRecordForLinkRespDataValidationError{
				field:  "ExpireTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInviteRecordForLinkRespDataMultiError(errors)
	}

	return nil
}

// CreateInviteRecordForLinkRespDataMultiError is an error wrapping multiple
// validation errors returned by
// CreateInviteRecordForLinkRespData.ValidateAll() if the designated
// constraints aren't met.
type CreateInviteRecordForLinkRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteRecordForLinkRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteRecordForLinkRespDataMultiError) AllErrors() []error { return m }

// CreateInviteRecordForLinkRespDataValidationError is the validation error
// returned by CreateInviteRecordForLinkRespData.Validate if the designated
// constraints aren't met.
type CreateInviteRecordForLinkRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteRecordForLinkRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteRecordForLinkRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteRecordForLinkRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteRecordForLinkRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteRecordForLinkRespDataValidationError) ErrorName() string {
	return "CreateInviteRecordForLinkRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteRecordForLinkRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteRecordForLinkRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteRecordForLinkRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteRecordForLinkRespDataValidationError{}

// Validate checks the field values on CreateInviteRecordForEmployeeReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateInviteRecordForEmployeeReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteRecordForEmployeeReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateInviteRecordForEmployeeReqMultiError, or nil if none found.
func (m *CreateInviteRecordForEmployeeReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteRecordForEmployeeReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOperatorUid() <= 0 {
		err := CreateInviteRecordForEmployeeReqValidationError{
			field:  "OperatorUid",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrgId() <= 0 {
		err := CreateInviteRecordForEmployeeReqValidationError{
			field:  "OrgId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInviteUserId() <= 0 {
		err := CreateInviteRecordForEmployeeReqValidationError{
			field:  "InviteUserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetInviteAccount()); l < 1 || l > 128 {
		err := CreateInviteRecordForEmployeeReqValidationError{
			field:  "InviteAccount",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateInviteRecordForEmployeeReq_InviteAccountType_NotInLookup[m.GetInviteAccountType()]; ok {
		err := CreateInviteRecordForEmployeeReqValidationError{
			field:  "InviteAccountType",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateInviteRecordForEmployeeReq_InviteEmployeeRole_NotInLookup[m.GetInviteEmployeeRole()]; ok {
		err := CreateInviteRecordForEmployeeReqValidationError{
			field:  "InviteEmployeeRole",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateInviteRecordForEmployeeReqMultiError(errors)
	}

	return nil
}

// CreateInviteRecordForEmployeeReqMultiError is an error wrapping multiple
// validation errors returned by
// CreateInviteRecordForEmployeeReq.ValidateAll() if the designated
// constraints aren't met.
type CreateInviteRecordForEmployeeReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteRecordForEmployeeReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteRecordForEmployeeReqMultiError) AllErrors() []error { return m }

// CreateInviteRecordForEmployeeReqValidationError is the validation error
// returned by CreateInviteRecordForEmployeeReq.Validate if the designated
// constraints aren't met.
type CreateInviteRecordForEmployeeReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteRecordForEmployeeReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteRecordForEmployeeReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteRecordForEmployeeReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteRecordForEmployeeReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteRecordForEmployeeReqValidationError) ErrorName() string {
	return "CreateInviteRecordForEmployeeReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteRecordForEmployeeReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteRecordForEmployeeReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteRecordForEmployeeReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteRecordForEmployeeReqValidationError{}

var _CreateInviteRecordForEmployeeReq_InviteAccountType_NotInLookup = map[enumv1.OrgInviteAccountTypeEnum_OrgInviteAccountType]struct{}{
	0: {},
}

var _CreateInviteRecordForEmployeeReq_InviteEmployeeRole_NotInLookup = map[enumv1.OrgEmployeeRoleEnum_OrgEmployeeRole]struct{}{
	0: {},
}

// Validate checks the field values on CreateInviteRecordForEmployeeResp with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateInviteRecordForEmployeeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteRecordForEmployeeResp
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateInviteRecordForEmployeeRespMultiError, or nil if none found.
func (m *CreateInviteRecordForEmployeeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteRecordForEmployeeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteRecordForEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteRecordForEmployeeRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteRecordForEmployeeRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInviteRecordForEmployeeRespMultiError(errors)
	}

	return nil
}

// CreateInviteRecordForEmployeeRespMultiError is an error wrapping multiple
// validation errors returned by
// CreateInviteRecordForEmployeeResp.ValidateAll() if the designated
// constraints aren't met.
type CreateInviteRecordForEmployeeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteRecordForEmployeeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteRecordForEmployeeRespMultiError) AllErrors() []error { return m }

// CreateInviteRecordForEmployeeRespValidationError is the validation error
// returned by CreateInviteRecordForEmployeeResp.Validate if the designated
// constraints aren't met.
type CreateInviteRecordForEmployeeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteRecordForEmployeeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteRecordForEmployeeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteRecordForEmployeeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteRecordForEmployeeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteRecordForEmployeeRespValidationError) ErrorName() string {
	return "CreateInviteRecordForEmployeeRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteRecordForEmployeeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteRecordForEmployeeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteRecordForEmployeeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteRecordForEmployeeRespValidationError{}

// Validate checks the field values on CreateInviteRecordForEmployeeRespData
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *CreateInviteRecordForEmployeeRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInviteRecordForEmployeeRespData
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateInviteRecordForEmployeeRespDataMultiError, or nil if none found.
func (m *CreateInviteRecordForEmployeeRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInviteRecordForEmployeeRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InviteId

	// no validation rules for InviteCode

	if all {
		switch v := interface{}(m.GetExpireTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInviteRecordForEmployeeRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInviteRecordForEmployeeRespDataValidationError{
					field:  "ExpireTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInviteRecordForEmployeeRespDataValidationError{
				field:  "ExpireTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AssignEmployeeId

	if len(errors) > 0 {
		return CreateInviteRecordForEmployeeRespDataMultiError(errors)
	}

	return nil
}

// CreateInviteRecordForEmployeeRespDataMultiError is an error wrapping
// multiple validation errors returned by
// CreateInviteRecordForEmployeeRespData.ValidateAll() if the designated
// constraints aren't met.
type CreateInviteRecordForEmployeeRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInviteRecordForEmployeeRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInviteRecordForEmployeeRespDataMultiError) AllErrors() []error { return m }

// CreateInviteRecordForEmployeeRespDataValidationError is the validation error
// returned by CreateInviteRecordForEmployeeRespData.Validate if the
// designated constraints aren't met.
type CreateInviteRecordForEmployeeRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInviteRecordForEmployeeRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInviteRecordForEmployeeRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInviteRecordForEmployeeRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInviteRecordForEmployeeRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInviteRecordForEmployeeRespDataValidationError) ErrorName() string {
	return "CreateInviteRecordForEmployeeRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInviteRecordForEmployeeRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInviteRecordForEmployeeRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInviteRecordForEmployeeRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInviteRecordForEmployeeRespDataValidationError{}

// Validate checks the field values on JoinByInviteLinkReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *JoinByInviteLinkReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JoinByInviteLinkReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// JoinByInviteLinkReqMultiError, or nil if none found.
func (m *JoinByInviteLinkReq) ValidateAll() error {
	return m.validate(true)
}

func (m *JoinByInviteLinkReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetInviteId() <= 0 {
		err := JoinByInviteLinkReqValidationError{
			field:  "InviteId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetInviteCode()); l < 1 || l > 128 {
		err := JoinByInviteLinkReqValidationError{
			field:  "InviteCode",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := JoinByInviteLinkReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserName()) < 1 {
		err := JoinByInviteLinkReqValidationError{
			field:  "UserName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserAvatar() != "" {

	}

	if m.GetUserPhone() != "" {

	}

	if m.GetUserEmail() != "" {

	}

	if len(errors) > 0 {
		return JoinByInviteLinkReqMultiError(errors)
	}

	return nil
}

// JoinByInviteLinkReqMultiError is an error wrapping multiple validation
// errors returned by JoinByInviteLinkReq.ValidateAll() if the designated
// constraints aren't met.
type JoinByInviteLinkReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JoinByInviteLinkReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JoinByInviteLinkReqMultiError) AllErrors() []error { return m }

// JoinByInviteLinkReqValidationError is the validation error returned by
// JoinByInviteLinkReq.Validate if the designated constraints aren't met.
type JoinByInviteLinkReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JoinByInviteLinkReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JoinByInviteLinkReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JoinByInviteLinkReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JoinByInviteLinkReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JoinByInviteLinkReqValidationError) ErrorName() string {
	return "JoinByInviteLinkReqValidationError"
}

// Error satisfies the builtin error interface
func (e JoinByInviteLinkReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJoinByInviteLinkReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JoinByInviteLinkReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JoinByInviteLinkReqValidationError{}

// Validate checks the field values on JoinByInviteLinkResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *JoinByInviteLinkResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JoinByInviteLinkResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// JoinByInviteLinkRespMultiError, or nil if none found.
func (m *JoinByInviteLinkResp) ValidateAll() error {
	return m.validate(true)
}

func (m *JoinByInviteLinkResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JoinByInviteLinkRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JoinByInviteLinkRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JoinByInviteLinkRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return JoinByInviteLinkRespMultiError(errors)
	}

	return nil
}

// JoinByInviteLinkRespMultiError is an error wrapping multiple validation
// errors returned by JoinByInviteLinkResp.ValidateAll() if the designated
// constraints aren't met.
type JoinByInviteLinkRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JoinByInviteLinkRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JoinByInviteLinkRespMultiError) AllErrors() []error { return m }

// JoinByInviteLinkRespValidationError is the validation error returned by
// JoinByInviteLinkResp.Validate if the designated constraints aren't met.
type JoinByInviteLinkRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JoinByInviteLinkRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JoinByInviteLinkRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JoinByInviteLinkRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JoinByInviteLinkRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JoinByInviteLinkRespValidationError) ErrorName() string {
	return "JoinByInviteLinkRespValidationError"
}

// Error satisfies the builtin error interface
func (e JoinByInviteLinkRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJoinByInviteLinkResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JoinByInviteLinkRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JoinByInviteLinkRespValidationError{}

// Validate checks the field values on JoinByInviteLinkRespData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *JoinByInviteLinkRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JoinByInviteLinkRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// JoinByInviteLinkRespDataMultiError, or nil if none found.
func (m *JoinByInviteLinkRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *JoinByInviteLinkRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrgId

	// no validation rules for UserId

	// no validation rules for EmployeeId

	// no validation rules for EmployeeName

	// no validation rules for EmployeeAvatar

	// no validation rules for EmployeeStatus

	// no validation rules for EmployeeRole

	if len(errors) > 0 {
		return JoinByInviteLinkRespDataMultiError(errors)
	}

	return nil
}

// JoinByInviteLinkRespDataMultiError is an error wrapping multiple validation
// errors returned by JoinByInviteLinkRespData.ValidateAll() if the designated
// constraints aren't met.
type JoinByInviteLinkRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JoinByInviteLinkRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JoinByInviteLinkRespDataMultiError) AllErrors() []error { return m }

// JoinByInviteLinkRespDataValidationError is the validation error returned by
// JoinByInviteLinkRespData.Validate if the designated constraints aren't met.
type JoinByInviteLinkRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JoinByInviteLinkRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JoinByInviteLinkRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JoinByInviteLinkRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JoinByInviteLinkRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JoinByInviteLinkRespDataValidationError) ErrorName() string {
	return "JoinByInviteLinkRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e JoinByInviteLinkRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJoinByInviteLinkRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JoinByInviteLinkRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JoinByInviteLinkRespDataValidationError{}

// Validate checks the field values on AgreeOrRefuseInviteReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AgreeOrRefuseInviteReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgreeOrRefuseInviteReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AgreeOrRefuseInviteReqMultiError, or nil if none found.
func (m *AgreeOrRefuseInviteReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AgreeOrRefuseInviteReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetInviteId() <= 0 {
		err := AgreeOrRefuseInviteReqValidationError{
			field:  "InviteId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetInviteCode()); l < 1 || l > 128 {
		err := AgreeOrRefuseInviteReqValidationError{
			field:  "InviteCode",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsAgree

	if m.GetUserId() <= 0 {
		err := AgreeOrRefuseInviteReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserName()) < 1 {
		err := AgreeOrRefuseInviteReqValidationError{
			field:  "UserName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserAvatar() != "" {

	}

	if m.GetUserPhone() != "" {

	}

	if m.GetUserEmail() != "" {

	}

	if len(errors) > 0 {
		return AgreeOrRefuseInviteReqMultiError(errors)
	}

	return nil
}

// AgreeOrRefuseInviteReqMultiError is an error wrapping multiple validation
// errors returned by AgreeOrRefuseInviteReq.ValidateAll() if the designated
// constraints aren't met.
type AgreeOrRefuseInviteReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgreeOrRefuseInviteReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgreeOrRefuseInviteReqMultiError) AllErrors() []error { return m }

// AgreeOrRefuseInviteReqValidationError is the validation error returned by
// AgreeOrRefuseInviteReq.Validate if the designated constraints aren't met.
type AgreeOrRefuseInviteReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgreeOrRefuseInviteReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgreeOrRefuseInviteReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgreeOrRefuseInviteReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgreeOrRefuseInviteReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgreeOrRefuseInviteReqValidationError) ErrorName() string {
	return "AgreeOrRefuseInviteReqValidationError"
}

// Error satisfies the builtin error interface
func (e AgreeOrRefuseInviteReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgreeOrRefuseInviteReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgreeOrRefuseInviteReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgreeOrRefuseInviteReqValidationError{}

// Validate checks the field values on AgreeOrRefuseInviteResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AgreeOrRefuseInviteResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgreeOrRefuseInviteResp with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AgreeOrRefuseInviteRespMultiError, or nil if none found.
func (m *AgreeOrRefuseInviteResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AgreeOrRefuseInviteResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AgreeOrRefuseInviteRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AgreeOrRefuseInviteRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AgreeOrRefuseInviteRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AgreeOrRefuseInviteRespMultiError(errors)
	}

	return nil
}

// AgreeOrRefuseInviteRespMultiError is an error wrapping multiple validation
// errors returned by AgreeOrRefuseInviteResp.ValidateAll() if the designated
// constraints aren't met.
type AgreeOrRefuseInviteRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgreeOrRefuseInviteRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgreeOrRefuseInviteRespMultiError) AllErrors() []error { return m }

// AgreeOrRefuseInviteRespValidationError is the validation error returned by
// AgreeOrRefuseInviteResp.Validate if the designated constraints aren't met.
type AgreeOrRefuseInviteRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgreeOrRefuseInviteRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgreeOrRefuseInviteRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgreeOrRefuseInviteRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgreeOrRefuseInviteRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgreeOrRefuseInviteRespValidationError) ErrorName() string {
	return "AgreeOrRefuseInviteRespValidationError"
}

// Error satisfies the builtin error interface
func (e AgreeOrRefuseInviteRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgreeOrRefuseInviteResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgreeOrRefuseInviteRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgreeOrRefuseInviteRespValidationError{}

// Validate checks the field values on AgreeOrRefuseInviteRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AgreeOrRefuseInviteRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgreeOrRefuseInviteRespData with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AgreeOrRefuseInviteRespDataMultiError, or nil if none found.
func (m *AgreeOrRefuseInviteRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *AgreeOrRefuseInviteRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrgId

	// no validation rules for UserId

	// no validation rules for EmployeeId

	// no validation rules for EmployeeName

	// no validation rules for EmployeeAvatar

	// no validation rules for EmployeeStatus

	// no validation rules for EmployeeRole

	if len(errors) > 0 {
		return AgreeOrRefuseInviteRespDataMultiError(errors)
	}

	return nil
}

// AgreeOrRefuseInviteRespDataMultiError is an error wrapping multiple
// validation errors returned by AgreeOrRefuseInviteRespData.ValidateAll() if
// the designated constraints aren't met.
type AgreeOrRefuseInviteRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgreeOrRefuseInviteRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgreeOrRefuseInviteRespDataMultiError) AllErrors() []error { return m }

// AgreeOrRefuseInviteRespDataValidationError is the validation error returned
// by AgreeOrRefuseInviteRespData.Validate if the designated constraints
// aren't met.
type AgreeOrRefuseInviteRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgreeOrRefuseInviteRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgreeOrRefuseInviteRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgreeOrRefuseInviteRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgreeOrRefuseInviteRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgreeOrRefuseInviteRespDataValidationError) ErrorName() string {
	return "AgreeOrRefuseInviteRespDataValidationError"
}

// Error satisfies the builtin error interface
func (e AgreeOrRefuseInviteRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgreeOrRefuseInviteRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgreeOrRefuseInviteRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgreeOrRefuseInviteRespDataValidationError{}
