// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/org-service/v1/resources/org_employee.resource.v1.proto

package resourcev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OrgEmployee with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrgEmployee) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrgEmployee with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrgEmployeeMultiError, or
// nil if none found.
func (m *OrgEmployee) ValidateAll() error {
	return m.validate(true)
}

func (m *OrgEmployee) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreatedTime

	// no validation rules for UpdatedTime

	// no validation rules for DeletedTime

	// no validation rules for EmployeeId

	// no validation rules for UserId

	// no validation rules for OrgId

	// no validation rules for OrgName

	// no validation rules for EmployeeAvatar

	// no validation rules for EmployeePhone

	// no validation rules for EmployeeEmail

	// no validation rules for EmployeeRole

	// no validation rules for EmployeeStatus

	// no validation rules for InviterRecordId

	// no validation rules for InviterUserId

	if len(errors) > 0 {
		return OrgEmployeeMultiError(errors)
	}

	return nil
}

// OrgEmployeeMultiError is an error wrapping multiple validation errors
// returned by OrgEmployee.ValidateAll() if the designated constraints aren't met.
type OrgEmployeeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgEmployeeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgEmployeeMultiError) AllErrors() []error { return m }

// OrgEmployeeValidationError is the validation error returned by
// OrgEmployee.Validate if the designated constraints aren't met.
type OrgEmployeeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgEmployeeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgEmployeeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgEmployeeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgEmployeeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgEmployeeValidationError) ErrorName() string { return "OrgEmployeeValidationError" }

// Error satisfies the builtin error interface
func (e OrgEmployeeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrgEmployee.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgEmployeeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgEmployeeValidationError{}
