// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	datatypes "gorm.io/datatypes"
	gorm "gorm.io/gorm"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// OrgRecordForUserSchema OrgRecordForUser
var OrgRecordForUserSchema OrgRecordForUser

// NewOrgRecordForUser new schema
func NewOrgRecordForUser() *OrgRecordForUser {
	return &OrgRecordForUser{}
}

const (
	TableName = "og_org_record_for_user"

	FieldUserId        = "user_id"
	FieldCreatedTime   = "created_time"
	FieldUpdatedTime   = "updated_time"
	FieldPersonalOrgId = "personal_org_id"
	FieldLastOrgId     = "last_org_id"
)

// OrgRecordForUser ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户组织记录'
type OrgRecordForUser struct {
	UserId        uint64    `gorm:"column:user_id;primaryKey;type:uint;autoIncrement;comment:用户ID" json:"user_id"`
	CreatedTime   time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime   time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	PersonalOrgId uint64    `gorm:"column:personal_org_id;type:uint;not null;default:0;comment:个人组织ID" json:"personal_org_id"`
	LastOrgId     uint64    `gorm:"column:last_org_id;type:uint;not null;default:0;comment:最后的组织ID" json:"last_org_id"`
}

// TableName table name
func (s *OrgRecordForUser) TableName() string {
	return TableName
}

// CreateTableMigrator create table migrator
func (s *OrgRecordForUser) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewCreateTable(migrator, migrationuitl.Version, s)
}

// DropTableMigrator create table migrator
func (s *OrgRecordForUser) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewDropTable(migrator, migrationuitl.Version, s)
}

// TableSQL table SQL
func (s *OrgRecordForUser) TableSQL() string {
	return `
create table og_org_record_for_user (
	user_id BIGINT unsigned auto_increment comment '用户ID',
	created_time DATETIME(3) not null comment '创建时间',
	updated_time DATETIME(3) not null comment '最后修改时间',
	personal_org_id BIGINT unsigned not null default 0 comment '个人组织ID',
	last_org_id BIGINT unsigned not null default 0 comment '最后的组织ID',
	primary key (user_id)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COMMENT '用户组织记录'
`
}
