// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"database/sql"
	"github.com/go-micro-saas/organization-service/app/org-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// OrgRepo repo
type OrgRepo interface {
	NewTransaction(ctx context.Context, opts ...*sql.TxOptions) gormpkg.TransactionInterface
	Create(ctx context.Context, dataModel *po.Org) error
	CreateWithTransaction(ctx context.Context, tx gormpkg.TransactionInterface, dataModel *po.Org) (err error)
	ExistCreate(ctx context.Context, dataModel *po.Org) (anotherModel *po.Org, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.Org, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.Org) error
	Update(ctx context.Context, dataModel *po.Org) error
	ExistUpdate(ctx context.Context, dataModel *po.Org) (anotherModel *po.Org, isNotFound bool, err error)
	QueryOneByOrgID(ctx context.Context, id uint64) (dataModel *po.Org, isNotFound bool, err error)
	QueryByOrgIDList(ctx context.Context, idList []uint64) ([]*po.Org, error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.Org, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.Org, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.Org, totalNumber int64, err error)
	ListOrg(ctx context.Context, queryParam *po.OrgListParam, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.Org, recordCount int64, err error)
	Delete(ctx context.Context, dataModel *po.Org) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
