// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"github.com/go-micro-saas/organization-service/app/org-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// OrgInviteRecordRepo repo
type OrgInviteRecordRepo interface {
	Create(ctx context.Context, dataModel *po.OrgInviteRecord) error
	ExistCreate(ctx context.Context, dataModel *po.OrgInviteRecord) (anotherModel *po.OrgInviteRecord, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.OrgInviteRecord, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.OrgInviteRecord) error
	Update(ctx context.Context, dataModel *po.OrgInviteRecord) error
	ExistUpdate(ctx context.Context, dataModel *po.OrgInviteRecord) (anotherModel *po.OrgInviteRecord, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.OrgInviteRecord, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.OrgInviteRecord, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.OrgInviteRecord, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.OrgInviteRecord, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.OrgInviteRecord) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
