// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"github.com/go-micro-saas/organization-service/app/org-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// OrgEmployeeRepo repo
type OrgEmployeeRepo interface {
	Create(ctx context.Context, dataModel *po.OrgEmployee) error
	CreateWithTransaction(ctx context.Context, tx gormpkg.TransactionInterface, dataModel *po.OrgEmployee) (err error)
	ExistCreate(ctx context.Context, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.OrgEmployee, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.OrgEmployee) error
	Update(ctx context.Context, dataModel *po.OrgEmployee) error
	ExistUpdate(ctx context.Context, dataModel *po.OrgEmployee) (anotherModel *po.OrgEmployee, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.OrgEmployee, isNotFound bool, err error)
	QueryOneByUserID(ctx context.Context, param *po.QueryEmployeeParam) (dataModel *po.OrgEmployee, isNotFound bool, err error)
	QueryOneByEmployeeID(ctx context.Context, employeeID uint64) (dataModel *po.OrgEmployee, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.OrgEmployee, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.OrgEmployee, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.OrgEmployee) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
